package main

import (
	"fmt"
	"strings"
	"time"
)

// Reporter generates human-readable markdown reports for task executions.
type Reporter struct{}

// GenerateReport converts a PipelineResult into a formatted Markdown document.
func (r *Reporter) GenerateReport(res *PipelineResult, workspace string) string {
	var sb strings.Builder

	sb.WriteString("# 🤖 CoderAgent Execution Report\n\n")

	sb.WriteString(fmt.Sprintf("**Task ID**: `%s`\n", res.TaskID))
	sb.WriteString(fmt.Sprintf("**Workspace**: `%s`\n", workspace))
	sb.WriteString(fmt.Sprintf("**Status**: %s\n", r.getStatusEmoji(res.Status)))
	sb.WriteString(fmt.Sprintf("**Efficacy**: %.1f/5.0\n", res.Efficacy))
	sb.WriteString(fmt.Sprintf("**Timestamp**: %s\n\n", time.Now().Format(time.RFC822)))

	sb.WriteString("## 📝 Execution Output\n")
	sb.WriteString("```text\n")
	sb.WriteString(res.Output)
	sb.WriteString("\n```\n\n")

	if res.Diff != "" {
		sb.WriteString("## 🔍 Code Changes (Diff)\n")
		sb.WriteString("```diff\n")
		sb.WriteString(res.Diff)
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("--- \n")
	sb.WriteString("*Generated by CoderAgent - Sovereign Mesh Integration*")

	return sb.String()
}

func (r *Reporter) getStatusEmoji(status string) string {
	switch status {
	case "SUCCESS":
		return "✅ SUCCESS"
	case "FAILURE":
		return "❌ FAILURE"
	case "PLAN_COMPLETE":
		return "🔄 PLAN_COMPLETE"
	default:
		return "❓ " + status
	}
}
